version: '3.8'

services:
  upward-habits:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/upward_habits.db
      - DEBUG=False
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    restart: unless-stopped

  # Optional: PostgreSQL for production
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: upward_habits
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Optional: Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: